
import type { Metadata } from "next";
import "@/app/globals.css";
import NavegationBar from "@/shared/ui/void/components/NavegationBar";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Void Labs | Ghost Client",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="es">
      <body suppressHydrationWarning>
        <div className="flex min-h-screen flex-col md:flex-row gap-2 md:gap-4 p-2 md:p-4">
          {/* Navegación Lateral */}
          <aside className="sticky top-0 z-40 w-full flex-none md:w-[320px]">
            <NavegationBar />
          </aside>

          {/* Área Principal */}
          <main className="flex-1 overflow-x-hidden">
            {children}
          </main>
        </div>
        <Toaster
          theme="dark"
          position="top-center"
          closeButton
          richColors
          duration={3000}
        />
      </body>
    </html>
  );
}
